const Field = widget => (label, name, { ...options }) => ({ label, name, ...options, widget })

export const StringField = Field('string')
export const DateTimeField = Field('datetime')
export const MarkdownField = Field('markdown')
export const BooleanField = Field('boolean')
export const DateField = Field('date')
export const FileField = Field('file')
export const HiddenField = Field('hidden')
export const ImageField = Field('image')
export const MapField = Field('map')
export const NumberField = Field('number')
export const ObjectField = Field('object')
export const RelationField = Field('relation')
export const SelectField = Field('select')
export const TextField = Field('text')
